export const GET_ALL_HEROES_LIST_SUCCESS = 'GET_ALL_HEROES_LIST_SUCCESS';
export const GET_ALL_HEROES_LIST_FAILURE = 'GET_ALL_HEROES_LIST_FAILURE';
export const GET_ALL_HEROES_LIST_START = 'GET_ALL_HEROES_LIST_START';
export const REQUEST_HEROES = 'REQUEST_HEROES';
export const CLEAR_ALL_HEROES_LIST = 'CLEAR_ALL_HEROES_LIST';
export const CHANGE_LIMIT_AND_PAGE = 'CHANGE_LIMIT_AND_PAGE';

export const GET_SELECTED_HERO_SUCCESS = 'GET_SELECTED_HERO_SUCCESS';
export const GET_SELECTED_HERO_FAILURE = 'GET_SELECTED_HERO_FAILURE';
export const GET_SELECTED_HERO_START = 'GET_SELECTED_HERO_START';
export const REQUEST_SELECTED_HERO = 'REQUEST_SELECTED_HERO';

export const GET_SEARCH_BOX_HINTS_SUCCESS = 'GET_SEARCH_BOX_HINTS_SUCCESS';
export const GET_SEARCH_BOX_HINTS_FAILURE = 'GET_SEARCH_BOX_HINTS_FAILURE';
export const GET_SEARCH_BOX_HINTS_START = 'GET_SEARCH_BOX_HINTS_START';
export const REQUEST_SEARCH_BOX_HINTS = 'REQUEST_SEARCH_BOX_HINTS';

export const GET_FILTER_HEROES_SUCCESS = 'GET_FILTER_HEROES_SUCCESS';
export const GET_FILTER_HEROES_FAILURE = 'GET_FILTER_HEROES_FAILURE';
export const GET_FILTER_HEROES_START = 'GET_FILTER_HEROES_START';
export const REQUEST_FILTER_HEROES = 'REQUEST_FILTER_HEROES';
