export const GET_HERO_SUCCESS = 'GET_HERO_SUCCESS';
export const GET_HERO_FAILURE = 'GET_HERO_FAILURE';
export const GET_HERO_START = 'GET_HERO_START';
export const REQUEST_HERO = 'REQUEST_HERO';

export const GET_ONE_HERO_SUCCESS = 'GET_ONE_HERO_SUCCESS';
export const GET_ONE_HERO_FAILURE = 'GET_ONE_HERO_FAILURE';
export const GET_ONE_HERO_START = 'GET_ONE_HERO_START';
export const REQUEST_ONE_HERO = 'REQUEST_ONE_HERO';
