export const GET_HERO_SUCCESS = 'GET_HERO_SUCCESS';
export const GET_HERO_FAILURE = 'GET_HERO_FAILURE';
export const GET_HERO_START = 'GET_HERO_START';
export const REQUEST_HERO = 'REQUEST_HERO';

export const GET_ONE_HERO_SUCCESS = 'GET_ONE_HERO_SUCCESS';
export const GET_ONE_HERO_FAILURE = 'GET_ONE_HERO_FAILURE';
export const GET_ONE_HERO_START = 'GET_ONE_HERO_START';
export const REQUEST_ONE_HERO = 'REQUEST_ONE_HERO';

export const GET_FILTER_HERO_SUCCESS = 'GET_FILTER_HERO_SUCCESS';
export const GET_FILTER_HERO_FAILURE = 'GET_FILTER_HERO_FAILURE';
export const GET_FILTER_HERO_START = 'GET_FILTER_HERO_START';
export const REQUEST_FILTER_HERO = 'REQUEST_FILTER_HERO';

export const GET_SEARCH_HERO_SUCCESS = 'GET_SEARCH_HERO_SUCCESS';
export const GET_SEARCH_HERO_FAILURE = 'GET_SEARCH_HERO_FAILURE';
export const GET_SEARCH_HERO_START = 'GET_SEARCH_HERO_START';
export const REQUEST_SEARCH_HERO = 'REQUEST_SEARCH_HERO';

export const CONCAT_HERO = 'CONCAT_HERO';
